### ISSUE TITLE
Does not assign a random port if the desired port is unavailable

### ISSUE THREAD

**Issue by thomas-alrek** [sindresorhus/get-port#31] opened 2019-04-11 13:55 UTC
Hello.

I am experiencing a issue.
If I have a server running on e.g http://localhost:8080, the following code still assigns me port 8080 instead of a random port:

```javascript
const getPort = require('get-port');

async function getRandomPort (preferredPort = 8080) {
  const port = await getPort({ port: preferredPort });
  return port;
}

getRandomPort(8080).then(port => console.log(port)); // 8080
```

**Comment by stroncium** [comment] 2019-04-11 15:23
```js
test('preferred port unavailable', async t => {
	const desiredPort = 8282;
	const server = net.createServer();
	await promisify(server.listen.bind(server))(desiredPort);

	const port = await getPort({port: desiredPort});
	t.is(typeof port, 'number');
	t.true(port > 0);
	t.not(port, desiredPort);
});
```

This test ensures this can't happen.
I also tried using another process(`http-server` from npm) to take port 8080 and your code gave me proper port(not 8080). Can you provide full reproduction steps, @thomas-alrek ?

**Comment by thomas-alrek** [comment] 2019-04-11 20:12
In my specific use case I have a Docker container running nginx, configured like this:

**Dockerfile**
```
FROM webdevops/php-nginx:7.2
ENV WEB_DOCUMENT_ROOT=/var/www/public
```

**docker-compose.yml**
```yaml
version: '2'
services:
  test:
    build: .
    ports:
      - '8080:80'
    volumes:
      - '/Users/thomas/development/test:/var/www'
```
So this container is not listening on port 8080.

I then have another project, where I am using get-port to assign a random port (but I prefer to have 8080 if available).

```javascript
const getPort = require('get-port');

getPort({ port: 8080 }).then(port => console.log(port));
```

Which still gives me 8080, instead of the expected random port.

**Comment by stroncium** [comment] 2019-04-11 23:42
I've tried to do exactly the same thing on linux and it still gave me proper(non-8080) port.

It semi-confirms my original idea that it is not related to `get-port`, but to networking setup. You seem to be using mac. I'm not sure how exactly docker is implemented for macs, but I found this:

> There is no docker0 bridge on macOS
> Because of the way networking is implemented in Docker Desktop for Mac, you cannot see a docker0 interface on the host. This interface is actually within the virtual machine.

It's a bit hard for me to understand how this whole concoction works, and I have no way to experiment, but I suspect that it is related to this fact, because if there is no interface for docker, then (if my assumption about macs are correct and they are same as linux in that regard) nothing prevents application from binding port which is bound in docker. However, it's not clear what happens to incoming connections then.

Could you please try to actually start a server from nodejs on this port(while your docker container is running) and report if it works and if not then what error it gives?

**Comment by stroncium** [comment] 2019-04-17 16:19
@thomas-alrek Any update on this?

**Comment by labsvisual** [comment] 2019-04-19 10:06
@stroncium, I can confirm this behavior. To reproduce this (on a macOS), run - for example - `nginx` and forward it to port `8080` with `docker run -p 8080:80 -d nginx:latest` and then try invoking `getPort()` with the preferred port as `8080`. 

```javascript
const getPort = require( 'get-port' );

async function bootstrap() {
	console.log( await getPort( {
		port: 8080
	} ) );
}

bootstrap();
```

I don't find taking this up as a fix; what do you think? 😄

**Comment by stroncium** [comment] 2019-04-19 16:10
@labsvisual Can you please provide me with additional info then? I don't have macos anywhere within reach.
> try to actually start a server from nodejs on this port(while your docker container is running) and report if it works and if not then what error it gives

**Comment by labsvisual** [comment] 2019-04-19 18:11
Sounds lovely. I didn't include it in that comment because I was still experimenting with the code. I have prepared a small test file for this which tests this behavior against a couple of versions of Node. 

I'll just collate everything I found out here.

**Comment by labsvisual** [comment] 2019-04-21 22:44
@stroncium, some updates.

---

I wrote a quick [`http-server`](https://github.com/labsvisual/libuv-server) in `libuv` to see if the problem was something inherent to Node.js. Turns out, it's not. If you build the project and run `./server` if there are no Docker/port conflicts, it just works. 

However, if you _do_ have something running on the port you get:
<img width="490" alt="Screen Shot 2019-04-22 at 4 12 30 AM" src="https://user-images.githubusercontent.com/13390457/56476416-e1669c80-64b4-11e9-8074-516f92783341.png">
and this is really interesting. At the lowest level, everything is jolly well; I am opening an issue on the core Node.js repository to see what others think. I would assume that this is **not** by design.

**Comment by stroncium** [comment] 2019-04-22 01:06
@labsvisual So, I take it you confirm the problem exists, but there is no error reported from nodejs?

If so, I can only guess there, as I still have no access to test machine, but could it be related to ipv6 vs ipv4? Your code does strict ipv4 bind, I've read nodejs source and your source + know that docker sets up only ipv4 networking be default.
Nodejs does try to bind to ipv6 `::` first, and only binds to `0.0.0.0` if failed. Your code goes straight to `0.0.0.0`. If ipv6 is in cat available they are expected to have different behavior.

**Comment by JeffyLo94** [comment] 2019-05-08 18:29
I encountered this issue as well. I can confirm it is an ipv6 vs ipv4 issue. 

Can this be a possible enhancement: add the option to specify ipv4 or ipv6 when checking the ports. Perhaps add it to your options?

As a temporary work around, if anyone else has issues with this, feel free to use this function as a check (note: this lacks the range features):

```Javascript
const net = require('net');
  getPort (startingPort = 1024, useIpv6 = false) {
    let ipVersion;
    ipVersion = useIpv6 ? '::' : '0.0.0.0';
    const server = net.createServer();
    return new Promise((resolve, reject) => server
    .on('error', error => error.code === 'EADDRINUSE' ? server.listen(++startingPort) : reject(error))
    .on('listening', () => server.close(() => resolve(startingPort)))
    .listen(startingPort, ipVersion))
  }
```

**Comment by stroncium** [comment] 2019-05-08 19:11
@JeffyLo94 You can just pass `host` option to `get-port`.

**Comment by Carrie999** [comment] 2019-07-04 06:54
```
(async () => {
	console.log(await getPort({host:'0.0.0.0',port: [3000,3001]}));
})();
```
it'is solved

**Comment by Aghassi** [comment] 2019-07-08 17:14
@stroncium What @Carrie999 posted does solve the issue. Can we either note it in the README or fold in the check that @JeffyLo94 added to the internal logic? This way, it is more automatic for folks who are unaware. Otherwise, the README can elaborate on the issue a little more so folks are aware they may need a `host` specified. I'm happy to contrib either, just looking to you guys to see what is preferred.

**Comment by stroncium** [comment] 2019-07-23 13:58
@Aghassi Not sure this will be the right way to go. Node.js core logic does exactly the same, so we're supposed to follow it I guess. Plus we don't actually break any promises, because the port you get can actually be used.

Generally, I think folks should be aware of how they configured their network when dealing with network apps, but that might be just me being annoyed.

@sindresorhus I think you should be the one to decide what we do about that.

**Comment by WormGirl** [comment] 2020-02-24 11:18
`(async () => {
  let port = await getPort({host: '0.0.0.0', port: getPort.makeRange(8080, 9000)})
  app.listen(port)
  console.log('- working on：' + chalk.cyan(`http://${ip.address()}:${port}`))
})();`

**Comment by stroncium** [comment] 2020-02-24 19:29
@sindresorhus this should probably be closed.

**Comment by patrick-tolosa** [comment] 2020-02-25 20:49
@stroncium  - I just recently stumbled upon this issue myself, could only solve it thanks to this open issue.

I think it should be included in the read me, at least as a gotcha.

**Comment by sindresorhus** [comment] 2020-02-27 19:22
PR welcome to update the readme.

**Comment by IamTheHttp** [comment] 2020-02-27 20:50
I opened a PR to update the read, happy to make changes where needed

**Comment by sindresorhus** [comment] 2020-03-06 16:36
@stroncium I've been thinking about this. Maybe we should just check both `::` and `0.0.0.0` by default if `host` option is not specified? That way it just works no matter what.

**Comment by stroncium** [comment] 2020-03-06 21:40
@sindresorhus but then results will be kinda incorrect, as there will be free port we don't use. Also, I don't exactly remember semantics here, but I think if you request a port on 0.0.0.0 it will be given even if it's taken on part(but not all) of v4 ips handled by host(so we will have same situation, but even more convoluted). But even without that, we will be introducing a leaky abstraction which is always bad imo. Educating people(who already try to write network software ffs) about what the network is and how it works seems like better idea.

**Comment by sindresorhus** [comment] 2020-03-09 09:00
> but then results will be kinda incorrect, as there will be free port we don't use. 

Yes, but I would argue it's better with a false-negative than a false-positive. This is just a simple tool to find a free port. It doesn't really matter if it's sometimes not actually taken.

> Educating people(who already try to write network software ffs) about what the network is and how it works seems like better idea.

That rarely works in practice. It's IMHO better to adjust to the expected behavior and clearly document everything.

**Comment by bgturner** [comment] 2020-12-23 19:45
I found this issue from a search engine and it helped me. I agree that this is an issue with the networking layer, but we made assumptions that turned out to bite us. To be specific, in our case, it wasn't IPv6/IPv4 differences, but instead `localhost`/`127.0.0.1` differences.

So for example, we originally wanted to make requests against: `127.0.0.1:4000` and asked for a port like:

```
		return {
			port: await getPort({
				port: 4000,
			})
		};
```

But in doing so, we encountered:

1. If something else is already listening on `localhost:4000` everything (ie our requests to `127.0.0.1:4000`) works fine
2. If something else is already listening on `127.0.0.1:4000`, the above code doesn't error, but it also doesn't indicate that the port is taken and in so doing, doesn't give a randomized port for us to use

Updating the above to include the specific port that we would be querying against fixed things:

```
		return {
			port: await getPort({
                                   host: '127.0.0.1',
				port: 4000,
			})
		};
```

Hope that helps others!

**Closed** 2021-10-03 16:39 UTC
Labels: bug, help wanted
